default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: anderson
  password: ae123

development:
  <<: *default
  database: nomina_api_development

test:
  <<: *default
  database: nomina_api_test

production:
  <<: *default
  database: nomina_api_production
